### ISSUE TITLE
addEventListener of None

### ISSUE THREAD

**Issue by rudrathegreat** [developedbyed/navbar-circle-animation#2]
Hi DevEd,

Testing my website on a localhost server on a Windows Laptop with Google Chrome and I am getting the following error -

```Javascript

Cannot read property 'addEventListener' of null

```

A little help pls

**Comment by kushagra-aa** [comment]
> Hi DevEd,
> 
> Testing my website on a localhost server on a Windows Laptop with Google Chrome and I am getting the following error -
> 
> ```js
> Cannot read property 'addEventListener' of null
> ```
> 
> A little help pls

It seems that document.getElementById('overlayBtn'); is returning null because it executes before the DOM fully loads.

If you put this line of code under

window.onload=function(){
  -- put your code here
}
then it will run without issue.

**Comment by rudrathegreat** [comment]
i somehow got it to work, can't remember how. But it works

**Comment by rudrathegreat** [comment]
thanks
